version: '3'
services:
  # firebase cli
  firebase:
    build: ./firebase
    env_file: .env
    volumes:
      - ../app/public:/app/public
      - ../app/.firebaserc:/app/.firebaserc
      - ../app/firebase.json:/app/firebase.json
      # function
      - ../src/firebase-functions/functions/src:/app/functions/src
      - ../src/firebase-functions/functions/tsconfig.json:/app/functions/tsconfig.json
      - ../src/firebase-functions/functions/tslint.json:/app/functions/tslint.json
      # functions auth
      - ./config/firebase/keys:/keys  
    ports:
      - 5000:5000
      - 9005:9005
    # command: [firebase, serve, -p, "5000", -o, "0.0.0.0", --token, "$FIREBASE_TOKEN", -P, "lostrpg-751c1", --only, hosting]

  # cssプリプロセッサ
  precss:
    build: ./precss
    volumes:
      - ./precss/app.js:/app/app.js
      - ../htdocs/css:/app/src
      - ../app/public/assets/css:/app/dest
    command: [npm, run, run]

# htmlテンプレートエンジン
  pug:
    build: ./pug
    volumes:
      - ../htdocs/pug:/app/src
      - ../app/public/lost:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]
  
  html2jade:
    build: ./html2jade
    volumes:
      - ../dist/lost:/app/src
      - ../app/public/lost:/app/dist

  # elm-dev:
  #   build: ./elm-dev
  #   volumes:
  #     - ./config/elm/webpack.config.js:/app/webpack.config.js
  #     - ../src/elm-spa:/app/src
  #     - ../src/elm-spa/assets:/app/assets
  #     - ../app/public/assets/js/forms:/app/dist
  #     - ../tests/elm-spa:/app/tests/tests
  #     - cache1:/app/elm-stuff
  #     - cache2:/app/tests/elm-stuff
  #   ports:
  #     - 3000:3000
  #   command: [yarn, dev]
  elm-singles:
    build: ./elm-singles
    volumes:
      - ./config/elm-singles/webpack.config.js:/app/webpack.config.js
      - ../src/elm-singles:/app/src
      - ../src/elm-singles/assets:/app/assets
      - ../app/public/assets/js/forms:/app/dist
      - ../tests/elm-singles:/app/tests/tests
      - cache1:/app/elm-stuff
      - cache2:/app/tests/elm-stuff
    ports:
      - 3000:3000
    command: [yarn, dev]

volumes:
  cache1: # 名前付きボリューム名
  cache2: