version: '3'
services:
  # firebase cli
  firebase:
    build: ./firebase
    env_file: .env
    volumes:
      - ../app/public:/app/public
      - ../app/.firebaserc:/app/.firebaserc
      - ../app/firebase.json:/app/firebase.json
    ports:
      - 5000:5000
      - 9005:9005
    command: [firebase, serve, -p, "5000", -o, "0.0.0.0", --token, "$FIREBASE_TOKEN"]

  # 構文チェック(ts)
  tslint:
    build: ./webpack
    volumes: 
      - ./config/tsconfig.json:/app/tsconfig.json
      - ./config/tslint.json:/app/tslint.json
      - ../src:/app/src
    command: [npm, run, -s, tslint, --, -c, tslint.json, 'src/**/*.ts', 'src/**/*.tsx']

  # Apiドキュメント
  typedoc:
    build: ./webpack
    volumes: 
      - ./config/tsconfig.json:/app/tsconfig.json
      - ../src:/app/src
      - ../dist/apidoc:/app/typedoc
    command: [npm, run, typedoc, --, --target, es6, --jsx, preserve, --ignoreCompilerErrors, --exclude, '**/*.test.ts', --out, ./typedoc/, ./src/]

  # ビルドツール
  webpack:
    build: ./webpack
    volumes:
      - ./config/.babelrc:/app/.babelrc
      - ./config/tsconfig.json:/app/tsconfig.json
      - ./config/webpack.config.babel.js:/app/webpack.config.babel.js
      - ../src/camp:/app/src
      - ../dist/bundle-webpack:/app/dist
      - ../public:/app/public
    environment:
      - NODE_ENV=develop
    command: [npm, run, dev-server, --, --history-api-fallback]
    ports:
      -  8080:8080

  # # トランスパイル(ts)
  # tsc:
  #   build: ./webpack
  #   volumes: 
  #     - ./config/tsconfig.json:/app/tsconfig.json
  #     - ../src:/app/src
  #     - ../dist/transpiled-tsc:/app/dist
  #   command: [npm, run, tsc]


  # # トランスパイル(babel)
  # babel:
  #   build: ./webpack
  #   volumes: 
  #     - ./config/.babelrc:/app/.babelrc
  #     - ../dist/transpiled-tsc:/app/src
  #     - ../dist/transpiled-babel:/app/dist
  #   depends_on:
  #     - tsc
  #   command: [npm, run, babel, --, src, -d, dist]
