version: '3'
services:
  # firebase cli
  firebase:
    build: ./firebase
    env_file: .env
    volumes:
      - ../app/react/public:/app/public
      - ../app/.firebaserc:/app/.firebaserc
      - ../app/firebase.json:/app/firebase.json
    ports:
      - 5000:5000
      - 9005:9005
    command: [firebase, serve, -p, "5000", -o, "0.0.0.0", --token, "$FIREBASE_TOKEN"]

  # cssプリプロセッサ
  precss:
    build: ./precss
    volumes:
      - ./precss/app.js:/app/app.js
      - ../htdocs/css:/app/src
      - ../app/public/assets/css:/app/dest
    command: [npm, run, run]

# htmlテンプレートエンジン
  pug:
    build: ./pug
    volumes:
      - ../htdocs/pug:/app/src
      - ../app/public/lost:/app/dist
    environment:
      - SHELL=/bin/bash
    command: [npm, run, watch]
  
  html2jade:
    build: ./html2jade
    volumes:
      - ../dist/lost:/app/src
      - ../app/public/lost:/app/dist

  elm-dev:
    build: ./elm-dev
    volumes:
      - ./config/elm/webpack.config.js:/app/webpack.config.js
      - ../src/elm:/app/src
      - ../dist/elm:/app/dist
    ports:
      - 3000:3000
    command: [yarn, dev]

  # s2sビルドツール
  s2s_build:
    build: ./s2s_build
    volumes:
      - ./config/s2s/.babelrc:/app/.babelrc
      - ./config/s2s/tsconfig.json:/app/tsconfig.json
      - ./config/s2s/tslint.json:/app/tslint.json
      - ./config/s2s/jest.config.js:/app/jest.config.js
      - ./config/s2s/webpack.config.babel.js:/app/webpack.config.babel.js
      - ../src/s2s/src:/app/src
      - ../src/s2s/packages:/app/dist
