version: '3'
services:
  # firebase cli
  firebase:
    build: ./firebase
    env_file: .env
    volumes:
      - ../app/public:/app/public
      - ../app/.firebaserc:/app/.firebaserc
      - ../app/firebase.json:/app/firebase.json
    ports:
      - 5000:5000
      - 9005:9005
    command: [firebase, serve, -p, "5000", -o, "0.0.0.0", --token, "$FIREBASE_TOKEN"]

  s2s:
    build: ./s2s
    volumes:
      - ../src/character:/app/s2s/examples/shopping-cart/src
      - ./config/flow/.flowconfig:/app/s2s/example/shopping-cart/.flowconfig
      - ./config/flow/s2s.config.js:/app/s2s/example/shopping-cart/s2s.config.js
    command: [yarn, run, s2s]

  webpack:
    build: ./webpack_flow
    volumes:
      - ../src/character:/app/src
      - ./config/flow/.flowconfig:/app/.flowconfig
      - ./config/flow/.babelrc:/app/.babelrc
      - ./config/flow/webpack.config.js:/app/webpack.config.js
      - ../public:/app/public
      - ../dist:/app/dist
    ports:
      -  8080:8080
    command: [npm, run, dev-server, --, --history-api-fallback]